### ISSUE TITLE
Evolution - proposer un getcapabilities avec ses propres données publiées

### ISSUE THREAD

**Issue by IGNF-Xavier** [IGNF/cartes.gouv.fr#173]
L'objectif est de proposer pour chaque service un getcapabilities statique filtré sur les données publiées par le producteur de données.
Cet getcapabilities serait enregistré en tant qu'annexes dans l'entrepôt.
Il serait proposé :

- dans l'espace logué de l'utilisateur : le (ou les) URL(s) et la possibilité de télécharger le xml
- dans la métadonnée de données : le (ou les) URL(s) pour permettre un rendu sur le catalogue.

**Comment by slafayIGN** [comment]
Le principe général a déjà été développé depuis un moment, les anomalies éventuelles constatées à posteriori ou par environnement sont dans d'autres issues.
