### ISSUE TITLE
Métadonnées et styles

### ISSUE THREAD

**Issue by IGNF-Xavier** [IGNF/cartes.gouv.fr#199]
Les workflow WFS et TMS permettent d'associer des fichiers de style aux services qui seront publiés.
Ces fichiers de style seront envoyés dans les annexes de l'entrepôt.

Il est possible de les référencer  : 

- Dans les métadonnées de données :
-- graphicOverview : permet de stocker une représentation de la donnée et le cas échéant les fichiers associés
-- portrayalCatalogueInformation : permet de référencer un SLD, sur un registre de symbologie avec une représentation et description
- Côté services : dans les GetCapabilities, il est possible de stocker cette info au niveau des liens vers les métadonnées (on peut en mettre plusieurs) en précisant par exemple que c’est du SLD :
<MetadataURL format="text/xml" type="TC211"> http://maMétadonnée19139</MetadataUrl>.
<MetadataURL format="text/xml" type="SLD"> http://monSLD</MetadataUrl>.
-- Pour le WFS, c'est directement le getcapabilities du service
-- pour le TMS, c'est https://data.geopf.fr/tms/1.0.0/LAYER (il y a une niveau au dessus derrière l'URL https://data.geopf.fr/tms/1.0.0 qui  référence tous les layers)

**Comment by ocruze** [comment]
La balise `graphicOverview` est pour la vignette normalement (c'est le cas actuellement).

Comment est-ce qu'on utilise la balise `portrayalCatalogueInformation` ? J'ai absolument rien trouvé sur internet concernant cette balise. 

Le seul moyen de spécifier les fichiers de style dans la métadonnée que j'ai trouvé jusque là, c'est de les spécifier comme des documents : 
![image](https://github.com/IGNF/cartes.gouv.fr/assets/33525693/50e828ab-94fa-4b2e-9168-a3b4b03be6b3)

**Comment by IGNF-Xavier** [comment]
Ok pour les mettre dans les documents.
De toute façon, nous n'avons pas de registre de styles.
Merci pour l'investigation et la proposition.

**Comment by IGNF-Xavier** [comment]
Comme liens document très bien.C'est la solution la plus raisonnable a défaut d'avoir une expertise autre ou la disponibilité d'un registre de style.Merci pour la proposition
Le 26 juin 2024 19:01, Orka Arnest CRUZE a écrit :


La balise `graphicOverview` est pour la vignette normalement (c'est le cas actuellement).

Comment est-ce qu'on utilise la balise `portrayalCatalogueInformation` ? J'ai absolument rien trouvé sur internet concernant cette balise. 

Le seul moyen de spécifier les fichiers de style dans la métadonnée que j'ai trouvé jusque là, c'est de les spécifier comme des documents : 
![image](https://github.com/IGNF/cartes.gouv.fr/assets/33525693/50e828ab-94fa-4b2e-9168-a3b4b03be6b3)

**Comment by AlexandreJaqua** [comment]
Ok en QUA : 
![image](https://github.com/IGNF/cartes.gouv.fr/assets/134588461/5c933f61-a014-481a-ab0b-08536c15add6)

![image](https://github.com/IGNF/cartes.gouv.fr/assets/134588461/fc63ea7f-319b-4cc0-95cd-ea41a9a80dc7)

**Comment by AlexandreJaqua** [comment]
Comme mis sur Teams : mea culpa, je me suis planté d'onglet, j'étais en dev. Ca marche du coup en dev ET en qua. On peut fermer. :)
