### ISSUE TITLE
Fiche de donnée, onglet Documents : lister les documents liés et les gérer

### ISSUE THREAD

**Issue by IGNF-Xavier** [IGNF/cartes.gouv.fr#211]
Permettre aux producteurs de la donnée de rajouter descriptif de contenus, descriptifs de livraisons, projets Qgis, etc.
Lister la documentation ainsi associée.

La documentation aura plusieurs formats : 

- des pdf
- des vidéos (lien videos)
- des pages html (soit des articles dans le CMS, soit du contenu plus statique en markdown dans ce dépôt ou un autre dépôt spécifique à la documentation)
- des projets Qgis

**Comment by slafayIGN** [comment]
Dans les métadonnées, les documents sont décrits avec le balisage XML suivant : 

```xml
<gmd:onLine type="style">
    <gmd:CI_OnlineResource>
        <gmd:linkage>
            <gmd:URL>{{ document_url }}</gmd:URL>
        </gmd:linkage>
        <gmd:name>
            <gco:CharacterString>{{ document_name }}</gco:CharacterString>
        </gmd:name>
        <gmd:description>
            <gco:CharacterString>{{ document_description }}</gco:CharacterString>
        </gmd:description>
    </gmd:CI_OnlineResource>
</gmd:onLine>
```

Il faut donc 3 éléments que l'utilisateur doit fournir : 
- une url
- un nom
- une description

Pour simplifier il n'y a que 2 types de documents : 
- ceux qui sont déjà en ligne quelque-part : dans ce cas on dispose d'une URL, et on peut éventuellement faciliter le remplissage du nom et de la description en allant chercher le document et en lisant ses balises meta (title et description) pour préremplir ces 2 champs.
- ceux qui ne sont pas déjà en ligne : dans ce cas on les téléverse en tant qu'annexe et l'utilisateur remplit également nom et description.

NB : La liste des documents tout comme les 2 variantes du formulaire d'ajout de document ne sont pas encore maquettées.
