### ISSUE TITLE
Application du style sur le WFS

### ISSUE THREAD

**Issue by IGNF-Xavier** [IGNF/cartes.gouv.fr#366]
### Description

Dans la partie visualiser les données, j'ai appliqué le style en 1.1.0 sur les forêts et j'ai eu l'erreur suivante : 
![image](https://github.com/IGNF/cartes.gouv.fr/assets/98382923/e37942c8-6df8-494e-a70b-b58e47be7f19)

[style_foret.zip](https://github.com/IGNF/cartes.gouv.fr/files/15236579/style_foret.zip)

**Comment by AlexandreJaqua** [comment]
![image](https://github.com/IGNF/cartes.gouv.fr/assets/134588461/631b9c59-90d3-4884-8362-437e23890f33)

J'ai toujours un message d'erreur vide avec un sld défaillant (ici j'ai changé la version en 2.1.0 ald 1.1.0)

**Comment by ocruze** [comment]
Je viens tout juste de déployer ce correctif. Peux-tu retester s'il te plaît ? Pourrais-tu nous envoyer le fichier sld s'il te plaît ?

**Comment by AlexandreJaqua** [comment]
Yes c'est mieux merci ! "sld version must be 1.0.0,1.1.0"

![image](https://github.com/IGNF/cartes.gouv.fr/assets/134588461/40e99eab-9924-4a40-9ba1-c82b930e7ec7)
