### ISSUE TITLE
Création d'une permission - services introuvables

### ISSUE THREAD

**Issue by AlexandreJaqua** [IGNF/cartes.gouv.fr#374]
J'essaye de créer une nouvelle permission en qualif' sur cartes.gouv - dev, et je me heurte à l'erreur suivante : 

![Image](https://github.com/IGNF/cartes.gouv.fr/assets/134588461/f4107105-2caa-4edf-b5c8-e5ca75c10f7a)

Je ne sais pas si les services sont invisibles/insélectionnables, ou si je n'ai pas le droit d'ouvrir de permission sur le moindre service. Dans les deux cas, il me manque ici une information, le message d'erreur n'est pas pertinent.

**Comment by slafayIGN** [comment]
![Image](https://github.com/IGNF/cartes.gouv.fr/assets/28899274/5ab4eb8c-425e-4108-9819-b20dc018be5a)

**Comment by AlexandreJaqua** [comment]
Impec, merci !
