### ISSUE TITLE
Modifier texte Demande de création d'un espace de travail

### ISSUE THREAD

**Issue by IGNF-Xavier** [IGNF/cartes.gouv.fr#397]
Sur la page de demande de création d'un espace de travail :
Modifier 
_Lorem ipsum, dolor sit amet consectetur adipisicing elit. Vel labore tempora id aspernatur culpa, ducimus repudiandae doloribus a doloremque, maiores fugit velit accusamus libero molestias?_

par 
```
Un espace de travail permet de disposer :
- d'un entrepôt permettant le stockage de données, fichiers statiques, configurations aux fins de définition et publication de géoservices
- d'une communauté d'utilisateurs pour laquelle vous pourrez gérer les droits de ses membres
suivant les modalités de l'offre "Essentiel".
```

(prévoir lien vers la page de l'offre)

**Comment by slafayIGN** [comment]
Lien vers la page offre ajouté (écrit "Essentielle" comme sur la page offre)

![Image](https://github.com/IGNF/cartes.gouv.fr/assets/28899274/0aa2e1b7-d985-4739-b28c-6e8604c7a908)

**Comment by IGNF-Xavier** [comment]
Nickel.
Merci
