### ISSUE TITLE
Ajouter un fil d'ariane

### ISSUE THREAD

**Issue by slafayIGN** [IGNF/cartes.gouv.fr#400]
Sur toutes les pages, publiques comme de l'espace privé, mettre un fil d'ariane systématiquement.

**Comment by slafayIGN** [comment]
@pprev94 , @ocruze 

- si possible pour les actualités `NewsArticle` : afficher une nouvelle propriété `breadcrumb` ou, si elle n'existe pas, le `title` de l'actualité
- si possible, mettre le `datasheet_name` dès qu'on est dans le contexte d'une fiche de données

@AlexandreJaqua tu peux quand même valider le principe, il y a des fils d'ariane partout.

**Comment by ocruze** [comment]
- actualités :
![image](https://github.com/IGNF/cartes.gouv.fr/assets/33525693/82a18c80-e3f1-486a-a5e7-c6aed75a637a)

- contexte d'une fiche de données :
![image](https://github.com/IGNF/cartes.gouv.fr/assets/33525693/efb184b2-96bc-4258-b5f2-77a4d2b9201f)

**Comment by IGNF-Xavier** [comment]
@AlexandreJaqua pour moi c'est bon. Je te laisse regarder.
merci
