### ISSUE TITLE
Erreur incompréhensible et Getcapabilities filtré non incrémenté

### ISSUE THREAD

**Issue by IGNF-Xavier** [IGNF/cartes.gouv.fr#404]
### Description

1. publication du service WFS depuis la fiche donnée ARBRE_IA : https://qlf-cartes.ign.fr/datastores/342f9301-d2a8-455f-adf5-e2cc73b90423/datasheet/ARBRE_IA avec la table ARBRE_ISOLE : SUCCES
2. publication du service WFS depuis la fiche donnée ARBRE_IA avec la table autre_ligneux

Je constate que : 

- Une erreur indique que le nom technique du service prérempli existe déjà. A priori, il ne faudrait pas que ce soit pré-rempli pour un nouveau service WFS
- Nom technique modifié, je vais jusqu'au bout du workflow : message d'erreur 
> une erreur est survenue
- sur l'onglet service : 
 - le service ia_gpkg_22-04-2024_wfs-3 est annoncé comme publié
 - le service ia_gpkg_22-04-2024_wfs-3 n'est pas visualisable https://qlf-cartes.ign.fr/datastores/342f9301-d2a8-455f-adf5-e2cc73b90423/service/d7c31793-8099-4a33-b864-9267c6a1cb52?datasheetName=ARBRE_IA  et le nom de la couche dans la visualisation n'est pas bon.
 - le service ia_gpkg_22-04-2024_wfs-3 n'est pas renseigné dans le getcapabilities filtré (https://data.geopf.fr/annexes/recette-cartes-gouv/gpf-geoserver-wfs/capabilities.xml) ni dans la fiche métadonnée ARBRE_IA

Le service ia_gpkg_22-04-2024_wfs-3 est bien sur https://data.geopf.fr/wfs/ows?VERSION=2.0.0 et utilisable sous Qgis

**Comment by AlexandreJaqua** [comment]
Le nom technique est toujours pré-rempli, mais on a une erreur à la validation de l'étape (donc au bon moment, je pense). L'erreur est explicite "ce nom technique existe déjà". Le fait de le laisse pré-rempli ne me semble pas abscons, ça permet de rajouter un petit "_autre_ligneux" à la fin par exemple ou toute autre mention inutile, je pense que ça aide à garder une cohérence entre les services.

Pour tout le reste du ticket, c'est bon : je retrouve bien ce service dans les Getcapa filtrées, dans les métadonnées, et le nom dans la visualisation c'est le bon.

OK en QUA 💹
