### ISSUE TITLE
 capabilities.xml filtré non créé ou mis à jour

### ISSUE THREAD

**Issue by IGNF-Xavier** [IGNF/cartes.gouv.fr#405]
### Description

- [ ] L'erreur sur le getcapabilities filtré : https://data.geopf.fr/annexes/recette-cartes-gouv/gpf-geoserver-wms-v/capabilities.xml

> > Whitelabel Error Page
> 
> This application has no explicit mapping for /error, so you are seeing this as a fallback.
> Thu Jun 06 07:21:06 GMT 2024
> There was an unexpected error (type=Not Found, status=404).
> Annexe inconnue

Depuis l'adresse du service de données copiée sur https://qlf-cartes.ign.fr/datastores/342f9301-d2a8-455f-adf5-e2cc73b90423/service/5c98bdc2-d5ed-489a-b638-f6615104e1e3?datasheetName=ARBRE_IA

- [ ] Une autre erreur "Erreur inconnue" apparait auparavant au moment de la publication du service WMS-v pourtant le service est bien publié et visualisable dans la page citée précédemment

**Comment by AlexandreJaqua** [comment]
Ok en QUA pour les deux erreurs.
