### ISSUE TITLE
AJouter le getcapabilities filtré dans la métadonnée

### ISSUE THREAD

**Issue by IGNF-Xavier** [IGNF/cartes.gouv.fr#410]
### Le besoin que vous rencontrez

- [x] rajouter le getcapabilities filtré dans la métadonnée générée.
- [x] s'assurer que le getcapabilities de chaque service filtré est enrichi par tous les services quelle que soit la fiche donnée.
- [ ] dans la métadonnée : positionner le getcapibilities filtré suivant le type en le titrant Service filtré "Nom du service"  (WFS, etc

**Comment by IGNF-Xavier** [comment]
QUA-SOCLE/csw?REQUEST=GetRecordById&SERVICE=CSW&VERSION=2.0.2&OUTPUTSCHEMA=http://standards.iso.org/iso/19115/-3/mdb/2.0&elementSetName=full&ID=ocsge_31_di_2022_toulouse_gpkg_25-06-2024_wfsTEST410 ne me donne aucun getcapabilities filtré.

Est-ce que c'est dû au fait que cela n'ait pas été implémenté sur le parcours du WFS? Même problème sur le WMS
Ou bien la feature n'a pas été déployée ?

Et je pense que le lien va arriver en tant que URL (donc dans la section du catalogue). Cela me va très bien, par contre il faudra le titrer avec "Getcapabilities filtré WFS" pour la version WFS

**Comment by AlexandreJaqua** [comment]
Ok bien implémenté sur les différents environnements.
Juste, on n'utilise nulle part le terme "filtre" ou "filtré" en tant que tel, on a par exemple "GetCapabilities - WFS", ça ne me semble pas problématique
