### ISSUE TITLE
Mineur - Affichage du bouton "désactiver" l'authentification forte à l'ajout d'une permission + lorem ipsum

### ISSUE THREAD

**Issue by AlexandreJaqua** [IGNF/cartes.gouv.fr#417]
**Contexte** : sur qlf-cartes, fiche ARBRE_IA25042024, je cherche à modifier les permissions du service WFS arbres_gpkg_09-10-2023_wmsv21_test_21221.
La page add-permission a ce petit souci graphique à la fin : 

![Image](https://github.com/IGNF/cartes.gouv.fr/assets/134588461/d79399f1-7c8f-4283-b204-add4f0ef534f)

Edit : aussi, il reste un lorem ipsum sur cette même page
![Image](https://github.com/IGNF/cartes.gouv.fr/assets/134588461/31549708-a4de-43d2-92ae-b1c2d52add9b)

La "licence" c'est bien juste le nom de la permission, c'est ça ? 
Faute de grande inspiration je propose "_Donner un nom explicite à votre permission._" (les autres instructions sur la même page sont à l'infinitif)

**Comment by IGNF-Xavier** [comment]
@AlexandreJaqua  A clore et ouvrir nouveau ticket dans MVP-Futur sur le problème d'affichage lié au DSFR.

**Comment by pprev94** [comment]
![Image](https://github.com/IGNF/cartes.gouv.fr/assets/22683027/8b96455e-f13b-4b56-9ddc-ebc0b07e30a1)

**Comment by slafayIGN** [comment]
Le problème d'affichage sur le toggle a bien été corrigé

![image](https://github.com/user-attachments/assets/cbe9e55f-34c2-4ea0-81bc-505a2b67046b)
