### ISSUE TITLE
TMS gestion du SLD

### ISSUE THREAD

**Issue by IGNF-Xavier** [IGNF/cartes.gouv.fr#420]
### Description

Sans ajout de style, le TMS est visible : 
![image](https://github.com/IGNF/cartes.gouv.fr/assets/98382923/308a9149-4d5c-4ecd-92ee-20ee79b2a15e)

Après avoir ajouté le style, le TMS n'est plus visible : 
![image](https://github.com/IGNF/cartes.gouv.fr/assets/98382923/2afe38af-b087-493e-aa9a-1b422ba876c5)

Il n'y a pas non plus l'adresse du style json qui est pourtant celle utilisée par Qgis. Il devrait y avoir un tel champ sur l'onglet diffuser le service

Ici je suis dans le datastore : a1e47cbf-b212-4a46-9b39-3fb3bb8f46d8
Données : OCS-GE Données intermédiaires
Adresse du service de données : https://data.geopf.fr/tms/1.0.0/OCSGE_DI_031_2022_IGN/{z}/{x}/{y}.pbf

### Comportement attendu

- [x] Visualiser les données avec le style appliqué
- [x] Disposer de l'URL de style dans l'onglet "Diffuser le service" copiable
- [ ] Support du SLD et du QML pour calculer le style

### Comment reproduire l'anomalie

C'est reproduisible sur le datastore : 342f9301-d2a8-455f-adf5-e2cc73b90423
Datasheet : ARBRE_IA25042024
TMS : ia_gpkg_11062024_tms-2
couche ia qui a le bon nom dans le SLD ci-joint
[style_ia2.zip](https://github.com/user-attachments/files/15803965/style_ia2.zip)

**Comment by ocruze** [comment]
- code de l'iframe et lien public vers la carte retirés
- liens vers les fichiers de style courant ajoutés

![image](https://github.com/IGNF/cartes.gouv.fr/assets/33525693/18d5dd3d-178d-44cb-ad19-9794c2c47cb0)

**Comment by slafayIGN** [comment]
@AlexandreJaqua Vérifier que le champ code html de l'iframe n'est plus là et que les champs pour les styles courants sont présents (plusieurs styles si plusieurs chouches en WFS, un seul en TMS)

**Comment by IGNF-Xavier** [comment]
Sur QUA
- [ ] Absence code HTML Iframe
- [ ] Style TMS
- [ ] Style WFS

**Comment by AlexandreJaqua** [comment]
![image](https://github.com/IGNF/cartes.gouv.fr/assets/134588461/4bd2d4cb-ae49-4c8b-acea-dc682fc026ad)

J'ai bien la mise en forme attendue pour mes deux styles, par contre je ne sais pas à quoi correspond le "undefined".

**Comment by AlexandreJaqua** [comment]
A priori, le "undefined" se produit si j'uploade un fichier sld, mais que j'en change avoir validé (ou que je reviens modifier le fichier sld utilisé). Comme si on ne listait pas ici (dans "diffuser le service") que les fichiers de style actifs

**Comment by slafayIGN** [comment]
On ne liste en effet dans les urls à copier que les styles actifs (ou courants), appliqués sur la carte à gauche. Lister tous les styles peut prendre beaucoup trop de place.

**Comment by AlexandreJaqua** [comment]
Oui justement c'est ce qui m'étonnait : qu'on ait des rémanences de styles non-utilisés.
Mais je n'arrive plus à reproduire l'erreur, ça m'a l'air résolu, merci !! :)

![image](https://github.com/IGNF/cartes.gouv.fr/assets/134588461/9c731dc1-5938-443c-9e45-bdc1e92197e0)

(image en ayant changé plusieurs fois de fichiers/styles, ce qui déclenchait largement l'erreur auparavant)
