### ISSUE TITLE
Fréquence de mise à jour dans les métadonnées

### ISSUE THREAD

**Issue by slafayIGN** [IGNF/cartes.gouv.fr#422]
(initialement dans #286)

Pour la fréquence de mise-à-jour : étape 3 sur 5 - Créer et publier un service WFS dans la partie Référence temporelle après le champ Date de la création de la ressource :

Titre : Fréquence de mise-à-jour

Texte d'aide ❓

Menu déroulant avec les options : 

| Valeur | Désignation | Définition |
| --- | --- | --- |
| continual | En continu | Les données sont mises à jour fréquemment et de manière répétée |
| daily | Journalier | Les données sont mises à jour chaque jour |
| weekly | Hebdomadaire | Les données sont mises à jour toutes les semaines |
| fortnightly | Bimensuel | Les données sont mises à jour toutes les deux semaines |
| monthly | Mensuel | Les données sont mises à jour tous les mois |
| quaterly | Trimestriel | Les données sont mises à jour tous les trimestres |
| biannually | Biannuel | Les données sont mises à jour deux fois par an |
| annually | Annuel | Les données sont mises à jour tous les ans |
| asNeeded | En fonction du besoin | Les données sont mises à jour en fonction du besoin |
| irregular | Irrégulier | Les données sont mises à jour à des intervalles de temps variables |
| notPlanned | Pas planifié | Il n’y a pas de plans pour la mise à jour des données |
| unknown | Inconnu | La fréquence de maintenance des données n’est pas connue |

Source : https://geoservices.ign.fr/sites/default/files/2021-12/DC_Metadonnees_2-0.pdf

**Comment by IGNF-Xavier** [comment]
Mise à jour depuis workflow : 

- [ ] WFS
- [ ] WMS
- [ ] WFS

**Comment by IGNF-Xavier** [comment]
Test en QUA : OK
