### ISSUE TITLE
Message d'erreur à améliorer - date de création de la ressource

### ISSUE THREAD

**Issue by AlexandreJaqua** [IGNF/cartes.gouv.fr#434]
Lors de la création d'un service, si j'oublie de remplir la date de création de la ressource, j'ai ce message d'erreur suivant : 

![Image](https://github.com/IGNF/cartes.gouv.fr/assets/134588461/c3bb1a4d-f796-47ba-88e0-71458b9e376c)

"creation_date must be a 'date' type, but the final value was: 'Invalid Date' (cast from the value '""')."

Puisque le format imposé du champ oblige, a priori, à être en JJ/MM/AAAA, on doit pouvoir remplacer ce message par la seule erreur possible : "ce champ est obligatoire"

**Comment by IGNF-Xavier** [comment]
Ok


![Image](https://github.com/IGNF/cartes.gouv.fr/assets/98382923/b6abf56f-f157-4e96-b1ca-6b0e908ea322)
