### ISSUE TITLE
Branchement du bac à sable "Découverte"

### ISSUE THREAD

**Issue by IGNF-Xavier** [IGNF/cartes.gouv.fr#436]
### Le besoin que vous rencontrez

Le modèle économique prévoit une offre découverte qui se branche à un datastore bac à sable.

### La solution que vous aimeriez

Le branchement effectif et la mise en place de tous les workflows disponibles de configuration de géoservices

**Comment by pprev94** [comment]
Il n'y a aucun label sur les stockages de l'entrepôt QLF Découverte de qualif

Il y a déjà un ticket [IGNGPF-3990] qui mentionne ce problème

**Comment by slafayIGN** [comment]
⚠️ Cassant pour les déploiements, des variables d'environnement changent de nom : 

`SERVICE_ACCOUNT_CLIENT_ID` et `SERVICE_ACCOUNT_CLIENT_SECRET` concernant le compte qui sert à ajouter automatiquement des membres dans la communauté identifiée par `SANDBOX_COMMUNITY_ID`, elles sont alors renommées respectivement en `SANDBOX_SERVICE_ACCOUNT_CLIENT_ID` et `SANDBOX_SERVICE_ACCOUNT_CLIENT_SECRET`.

Et 2 variables d'environnement sont ajoutées : `SANDBOX_PROC_INT_VECT_FILES_DB` et `SANDBOX_PROC_CREATE_VECT_PYR`.

De manière générale, toutes les variables d'environnement qui ne concernent que le bac à sable sont préfixées `SANDBOX_`

**Comment by AlexandreJaqua** [comment]
Hello,
Pour info, le bac à sable semble opérationnel via l'API, nous sommes parvenus à mettre des données en base puis à créer des services DOWNLOAD, WFS, WMS-V, WMS-R, et WMTS. Les aspects gestion des droits, gestion des permissions, et blocage des partages inter-datastores semblent opérationnels aussi.
Par contre je ne parviens pas à mettre en base via l'interface cartes.gouv : le traitement d'intégration reste indéfiniment "en attente". Est-ce causé par les différences de variables que tu mentionnes Sylvain ?

**Comment by AlexandreJaqua** [comment]
@ocruze Est-ce que tu pourrais apporter une réponse sur le message précédent, en l'absence de Sylvain stp ?

**Comment by slafayIGN** [comment]
L'intégration réussie mais la publication d'un service échoue avec le message suivant : `Le layer_name de la configuration doit être préfixé par SANDBOX` qui a été signalé le 23 juillet par Victor (IGNGPF-4149) et corrigé le 1er août.
Il ne faut pas compter sur l'utilisateur pour ajouter ce préfixe lui-même, il faut faire évoluer notre système de publication en traitant ce cas particulier.

**Comment by slafayIGN** [comment]
La demande a été doublonnée et traitée par #503
