### ISSUE TITLE
Pas de retours à cartes.gouv après réinitialisation MDP

### ISSUE THREAD

**Issue by IGNF-Xavier** [IGNF/cartes.gouv.fr#437]
### Description

Clic sur URL de réinitialisation de mot de passe depuis le mail adhoc
Complétion 2X du nouveau mot de passe
Validation
Résultat : 
![image](https://github.com/IGNF/cartes.gouv.fr/assets/98382923/1967e355-d612-471a-9397-064bf811e7ad)

### Comportement attendu

Revenir à cartes.gouv

**Comment by NicoLeclercIGN** [comment]
Hello,

Je ne suis pas parvenu à reproduire le bug.
Voici mon test :
- Test sur FF 115.7.0esr (32 bits) config IGN, Version 123.0.6312.59 (Build officiel) (32 bits) install portable et Edge Version 129.0.2792.52 (Version officielle) (64 bits) config IGN
- Je démarre sur chaque navigateur cache vidé pour éviter tout effet de bord
- J'utilise mon compte perso en @gmail.com
- Je clique sur le bouton connexion de cartes.gouv puis le lien de mot de passe oublié. je suis le process
- J'ouvre Gmail dans un onglet nouveau du navigateur testé
- Je clique sur le lien (nouvel onglet cartes.gouv s'ouvre)
- Réinitialisation du mdp dans cet onglet
- en sortie j'arrive sur mon tableau de bord avec mon/mes espaces de travail

Bref je mettrai bien une pièce sur un cookie de session qui colle ou est quelque part dans un cache navigateur

**Comment by slafayIGN** [comment]
Merci @NicoLeclercIGN pour la tentative de reproduction du bug.

J'archive sans correction devant l'impossibilité d'identifier la cause et parce que la procédure reste généralement fonctionnelle.
