### ISSUE TITLE
Absence de l'organisme sur le catalogue

### ISSUE THREAD

**Issue by IGNF-Xavier** [IGNF/cartes.gouv.fr#440]
### Description

Dans alim/diff, l'organisme est bien renseigné
![image](https://github.com/IGNF/cartes.gouv.fr/assets/98382923/2dc21154-f6f6-4ade-a548-c01690c7c28c)

Dans le catalogue, l'organisme ne ressort pas
![image](https://github.com/IGNF/cartes.gouv.fr/assets/98382923/118f5598-2597-41ef-8df3-cf6ae3bdec13)

**Comment by IGNF-Xavier** [comment]
A priori c'est sur contact pour la ressource que le datahub pointe : 


![Image](https://github.com/IGNF/cartes.gouv.fr/assets/98382923/1279b5c3-219f-4246-a9b4-bce99d864a24)


Soit 
```
<gmd:pointOfContact>
<gmd:CI_ResponsibleParty>
<gmd:organisationName>
<gco:CharacterString>SCHAPI - Service d'hydrométéorologie et d'appui à la prévision des inondations</gco:CharacterString>
</gmd:organisationName>
<gmd:contactInfo>
<gmd:CI_Contact>
<gmd:address>
<gmd:CI_Address>
<gmd:electronicMailAddress>
<gco:CharacterString>Adh.Schapi.Srnh.Dgpr@developpement-durable.gouv.fr</gco:CharacterString>
</gmd:electronicMailAddress>
</gmd:CI_Address>
</gmd:address>
</gmd:CI_Contact>
</gmd:contactInfo>
<gmd:role>
<gmd:CI_RoleCode codeList="http://standards.iso.org/iso/19139/resources/gmxCodelists.xml#CI_RoleCode" codeListValue="custodian">custodian</gmd:CI_RoleCode>
</gmd:role>
</gmd:CI_ResponsibleParty>
</gmd:pointOfContact>
```

**Comment by AlexandreJaqua** [comment]
![image](https://github.com/IGNF/cartes.gouv.fr/assets/134588461/a76f6ebc-c876-4322-bca3-1027c5b97c56)

Pour moi c'est bon en QUA !
