### ISSUE TITLE
Erreur 500 à la publication du WMS-vecteur et DU TMS

### ISSUE THREAD

**Issue by IGNF-Xavier** [IGNF/cartes.gouv.fr#441]
### Description

Sur cartes.mut-dev une erreur 500 apparait quand on publie en WMS-V

Informations techniques : 
`entrepot/02787fa4-826e-4022-83e3-86f094c95c60/service/wms-vecteur/1d4cbc84-42b1-421d-a1f5-91b7f04c128e/modification?vectorDbId=83792768-858a-4b38-8154-17490b225fa6`

Pour autant le flux est quand même publié...

**Comment by IGNF-Xavier** [comment]
Même problème avec la version 0.4.4

**Comment by slafayIGN** [comment]
Dans les 2 environnements DEV et QUA ?

**Comment by IGNF-Xavier** [comment]
Qua aussi

**Comment by slafayIGN** [comment]
Avec la suppression de la dépendance à une url geonetwork non disponible en qua, le problème ne devrait plus se produire

**Comment by AlexandreJaqua** [comment]
Ok sur qlf aussi, plus d'erreur 500 et j'ai vérifié la viabilité des données. Je ferme.
