### ISSUE TITLE
Erreur 500 IGN-MUT en QUA à cause de la non exposition de geonetwork

### ISSUE THREAD

**Issue by IGNF-Xavier** [IGNF/cartes.gouv.fr#444]
### Description

A la publication du WFS, j'ai l'erreur 500 suivante : 
![image](https://github.com/IGNF/cartes.gouv.fr/assets/98382923/6cd4cb78-160e-45ba-a8b4-47b6828d1078)

Pour autant le WFS est publié
https://qlf-cartes.ign.fr/entrepot/a1e47cbf-b212-4a46-9b39-3fb3bb8f46d8/service/wfs/ajout?vectorDbId=7f36a324-f9d8-4abd-b8a9-ca033cdbb6ee

**Comment by IGNF-Xavier** [comment]
Erreur 500 sur https://qlf-cartes.ign.fr/api/datastores/a1e47cbf-b212-4a46-9b39-3fb3bb8f46d8/stored_data/426fefe7-5e8e-4f6a-b21e-fcdeaf89e4f7/wfs/ au moment de la publication WFS Tout public


```
{
    "type": "https:\/\/tools.ietf.org\/html\/rfc2616#section-10",
    "title": "An error occurred",
    "status": 500,
    "detail": "Internal Server Error"
}
```

![image](https://github.com/IGNF/cartes.gouv.fr/assets/98382923/1cdc90fe-6312-4a39-ae33-41eab0455bf4)

**Comment by AlexandreJaqua** [comment]
Testé et validé sur IGN-MUT : plus d'erreur 500, les données sont bien complètes. @IGNF-Xavier je te laisserai fermer ?
