### ISSUE TITLE
Mettre une modale de confirmation de suppression des styles

### ISSUE THREAD

**Issue by IGNF-Xavier** [IGNF/cartes.gouv.fr#445]
### Le besoin que vous rencontrez

Pour la suppression, une modale de confirmation lors du clic sur la poubelle  serait plus safe
![image](https://github.com/IGNF/cartes.gouv.fr/assets/98382923/d3638fd1-8496-42f6-b416-92ebaced01d7)

**Comment by slafayIGN** [comment]
![Image](https://github.com/IGNF/cartes.gouv.fr/assets/28899274/fd95b4d3-0d37-4216-ba57-056f2c61eea6)

**Comment by IGNF-Xavier** [comment]
Ok. Super
