### ISSUE TITLE
Supprimer la recherche de la version des fichiers SLD avant lecture par le parseur de geostyler

### ISSUE THREAD

**Issue by pprev94** [IGNF/cartes.gouv.fr#446]
### Description

Dans l'ancienne version du parseur SLD de Geostyler, la version était dans les options et était utilisée dans la lecture.
Depuis la version 5.4.0 la version du fichier SLD est recherchée directement dans le fichier.

La recherche de la version avant lecture est donc inutile

### Comportement attendu

Supprimer la recherche de la version avant la lecture par le parser SLD

**Comment by ocruze** [comment]
Parfait !
