### ISSUE TITLE
Chargement des pages problématiques

### ISSUE THREAD

**Issue by IGNF-Xavier** [IGNF/cartes.gouv.fr#447]
Sur cartes.mut-dev, nous retrouvons le problème d'affichage de pages sur IE : 

![Image](https://github.com/IGNF/cartes.gouv.fr/assets/98382923/678c317e-b8b6-41bc-8c3e-3c6201260f1d)

Auparavant, c'était un problème lié aux sondes, est-ce encore le cas?

**Comment by IGNF-Xavier** [comment]
Je vais mettre cela sur le compte du VPN

**Comment by slafayIGN** [comment]
Quel était le problème d'affichage exactement ?
Un temps de chargement anormalement long ?

**Comment by IGNF-Xavier** [comment]
Oui anormalement long.
Mais pas eu de nouvelles de MARS ou du SOI pour déterminer si ce n'était pas lié aux conf réseaux.
A voir si en prod, on rencontre le problème
