### ISSUE TITLE
Erreur 500 au chargement de l'onglet métadonnée

### ISSUE THREAD

**Issue by IGNF-Xavier** [IGNF/cartes.gouv.fr#448]
### Description

Sur qlf-cartes.ign.fr, une erreur 500 aparait pour l'onglet métadonnée et la patience continue de tourner 

https://qlf-cartes.ign.fr/api/datastores/a1e47cbf-b212-4a46-9b39-3fb3bb8f46d8/metadata/OCS-GE%20Donn%C3%A9es%20interm%C3%A9diaires

![image](https://github.com/IGNF/cartes.gouv.fr/assets/98382923/ad2cfc37-0931-4fcb-8cae-28789f10a628)

Contenu de la réponse : 
<!DOCTYPE html>
```
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="robots" content="noindex,nofollow,noarchive" />
    <title>An Error Occurred: Internal Server Error</title>
    <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>❌</text></svg>" />
    <style>body { background-color: #fff; color: #222; font: 16px/1.5 -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif; margin: 0; }
.container { margin: 30px; max-width: 600px; }
h1 { color: #dc3545; font-size: 24px; }
h2 { font-size: 18px; }</style>
</head>
<body>
<div class="container">
    <h1>Oops! An Error Occurred</h1>
    <h2>The server returned a "500 Internal Server Error".</h2>

    <p>
        Something is broken. Please let us know what you were doing when this error occurred.
        We will fix it as soon as possible. Sorry for any inconvenience caused.
    </p>
</div>
</body>
</html>
```

### Comportement attendu

Charger la fiche de données et avoir les métadonnée de la fiche de donnée

### Comment reproduire l'anomalie

Se rendre dans son espace personnel,
charger une des données de son entrepôt
constater

**Comment by IGNF-Xavier** [comment]
Même problème sur cartes.mut-dev

**Comment by AlexandreJaqua** [comment]
Testé et validé, sur mutdev et qlf. Je me permets de fermer, merci !
