### ISSUE TITLE
QLF - le menu pour le TMS est incorrect

### ISSUE THREAD

**Issue by IGNF-Xavier** [IGNF/cartes.gouv.fr#450]
### Description

![image](https://github.com/IGNF/cartes.gouv.fr/assets/98382923/f88d16eb-998c-49bb-9237-908162bcfb7e)

_Copier l'URL de diffusion_ ne donne que le nom du TMS
_Mettre à jour la légende_ ne fonctionne pas 

ne fonctionne pas

### Comportement attendu

- [ ] _Copier l'URL de diffusion_ doit donner l'URL
- [ ] _Mettre à jour la légende_  doit fonctionner mais pour le MVPJune24 à désactive

### Comment reproduire l'anomalie

Aller dans la fiche données onglet services et constater

**Comment by slafayIGN** [comment]
Sur la page de visu du service, tu peux voir que l'URL de ce service en particulier est indisponible. Mais on aurait dû le mettre aussi dans ce menu.

Ceci est dû à ces données en particulier qui contiennent des sauts de ligne codés `\n` dans le champ `infobulle` => cela entraine la génération d'un fichier `metadata.json` invalide et c'est dans ce fichier qu'on cherche l'URL du service.

Le fichiers metadata invalide : https://data.geopf.fr/tms/1.0.0/bruit_multi_gpkg_24-06-2024-3_tms/metadata.json*

Ce problème a été remonté le 24 avril dans **IGNGPF-3673** avec comme exemple un autre fichier de metadata : https://data-qua.priv.geopf.fr/tms/1.0.0/tms_desc_carac_spe/metadata.json. Fichier dans lequel nous avions introduit des sauts de ligne en description. C'est d'ailleurs à cause de ce problème que nous ne remplissons pas la description dans le metadata.json (sur ton nouveau service on a mis un "." dans ce champ).

*Note que tes données, outre les sauts de ligne, ont un pb d'encodage également pour ce même champ `infobulle` : [requête WFS](https://data.geopf.fr/wfs?SERVICE=WFS&REQUEST=GetFeature&VERSION=2.0.0&typeNames=bruit_multi_gpkg_24-06-2024_wfs:bruit_multi&outputFormat=application/json&srsname=EPSG:3857&bbox=2.5511779217900195,50.431334605523375,3.5130798902099802,50.85830749772501,EPSG:4326) contenant des valeurs comme : 
```
Carte: BRUIT Multi-Expositions (2019)\nType: A (Niveau d'exposition)\nP�riode: JOUR\nNiveau: 50 � 55 dB
```

**Comment by slafayIGN** [comment]
à tester en DEV ou QUA :
- bouton pour mettre à jour la légende désactivé
- message d'url de diffusion indisponible lorsque metadata.json est invalide

**Comment by IGNF-Xavier** [comment]
Le bouton pour mettre la légende a même disparu
