### ISSUE TITLE
Enregistrement du lien de géoservice dans la métadonnée

### ISSUE THREAD

**Issue by IGNF-Xavier** [IGNF/cartes.gouv.fr#452]
### Description

Je constate que sur le catalogue : QLF-Cartes/catalogue/dataset/OCSGE_DI_

Les requêtes pour afficher le WMTS ont un paramétrage doublé :
`https://data.geopf.fr/wms-v?SERVICE=WMS&SERVICE=WMS&VERSION=1.3.0&VERSION=1.3.0&request=GetCapabilities&REQUEST=GetMap&FORMAT=image/png&STYLES=&TRANSPARENT=true&LAYERS=OCSGE_DI_031_2022&TILED=true&WIDTH=256&HEIGHT=256&CRS=EPSG:3857&BBOX=157766.02638060227,5395231.204480881,158071.77449374297,5395536.952594021`

Ce qui est reconnue par la GPF comme une mauvaise requête et donc n'affiche rien.

Pour autant la ressource est bien publié et disponible : QLF-Cartes/entrepot/a1e47cbf-b212-4a46-9b39-3fb3bb8f46d8/service/387bc1bb-46cf-4982-84ef-acc2dc1c59c7/visualisation?datasheetName=OCS-GE%20Donn%C3%A9es%20interm%C3%A9diaires

et les requêtes sont bonnes : https://data.geopf.fr/wms-v?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=OCSGE_DI_USAGE_031_2022_IGN&WIDTH=256&HEIGHT=256&CRS=EPSG%3A3857&STYLES=&BBOX=136975.15468703583%2C5342031.032794397%2C156543.03392804094%2C5361598.912035403

### Comportement attendu

Que cela s'affiche

### Comment reproduire l'anomalie

Allez sur le datahub

### Solution possible

Résolution de IGNGPF-3856

**Comment by ocruze** [comment]
On enregistre l'URL de getcap dans la métadonnée. C'est le cas depuis un moment et les flux WMS s'affichaient bien sur le catalogue avant.

**Comment by IGNF-Xavier** [comment]
Comme indiqué la solution possible est a priori au niveau de IGNGPF-3856.
La GPF est devenue intransigeante sur les paramètres de requêtes depuis le 9 juin. C'est une régression quand on sait que la plupart des logiciels ou bibliothèque reconstruisent les URLs d'appel aux services OGC et dans notre cas, doublonne les pramètres VERSION et SERVICE

**Comment by slafayIGN** [comment]
ça pourrait également être remonté comme une évolution sur datahub.
En reconstruisant les URLs pour affichage, il pourrait nettoyer les URLs des paramètres en doublon.

Je remarque quand même que pour d'autre données, cela s'affiche car ce n'est pas le lien vers le GetCapabilities qui est enregistré dans les métadonnées mais bien la racine du service. Par exemple sur la fiche de https://qlf-cartes.ign.fr/catalogue/dataset/IGNF_OCS_GE_1-1.xml, le lien vers le WMTS de la couche `OCSGE.CONSTRUCTIONS` est `https://data.geopf.fr/wmts`.
Est-ce que mettre l'url du GetCapabilities n'était pas une mauvaise consigne ?

Il y a donc 3 solutions possibles (et elles sont peut-être toutes souhaitables) :
- au niveau des services : tolérer les paramètres en doublon
- au niveau de l'affichage datahub : ne pas générer de requêtes avec des paramètres en doublon
- au niveau de la création de la métadonnée : ne mettre aucun paramètre dans l'url du service

**Comment by IGNF-Xavier** [comment]
Oui le problème est que c'est devenu plus restrictif côté GPF.C'est identifié et pas de notre côté.Je devais l'ouvrir pour l'identifier.
Le 26 juin 2024 19:26, Orka Arnest CRUZE a écrit :


On enregistre l'URL de getcap dans la métadonnée. C'est le cas depuis un moment et les flux WMS s'affichaient bien sur le catalogue avant.

**Comment by IGNF-Xavier** [comment]
au niveau de la création de la métadonnée : ne mettre aucun paramètre dans l'url du service : c'est à ton niveau @slafayIGN
au niveau des services : IGNGPF3856
Au niveau du datahub : Ticket 919

**Comment by IGNF-Xavier** [comment]
Changement de milestones car l'une des corrections est faite

**Comment by slafayIGN** [comment]
Puisque la dernière correction concerne en réalité geonetwork-ui. Son suivi ici ne me semble plus nécessaire.
