### ISSUE TITLE
Faciliter l'ajout d'utilisateur

### ISSUE THREAD

**Issue by IGNF-Xavier** [IGNF/cartes.gouv.fr#457]
LE mail de demande d'ajout est reçu

![Image](https://github.com/IGNF/cartes.gouv.fr/assets/98382923/802ed179-0fdd-425c-ad53-aa10c7ea30ab)

- [x] Solution de contournement : renvoyer vers le tutoriel pour l'ajout d'utilisateur depuis ce mail
- [x] Solution cible : lien qui permet d'aller sur la modale d'ajout préremplie avec l'uuid utilisateur (en passant par étape de connexion si session inactive)

**Comment by slafayIGN** [comment]
Le lien d'ajout direct a pourtant déjà été prévu dans #222 (et #133) :
![image](https://github.com/IGNF/cartes.gouv.fr/assets/28899274/ab8685d0-e6a1-463c-83b0-b09ff57a1ad5)
Un lien de cette forme mène à la page de gestion des membres avec la modale d'ajout ouverte et le champ _Identifiant de l'utilisateur_ rempli : `/entrepot/{uuid-entrepot}/membres?userId={uuid-utilisateur}`

Il reste à l'ajouter dans le template de mail envoyé à l'adresse de contact de la communauté : https://github.com/IGNF/cartes.gouv.fr/blob/45f92a1ed979186bb0f66a3eb43e9a96758b4a2e/templates/Mailer/join_community.html.twig

**Comment by pprev94** [comment]
@IGNF-Xavier  Peux-tu préciser le contenu du mail stp ? Merci

**Comment by IGNF-Xavier** [comment]
Bonjour,

Un utilisateur demande à rejoindre "DEMO_IGN_SPP" (id=33c2c13d-353d-4d88-a557-19e90e741841)

Informations sur le demandeur :
Adresse mail : azerty@ign.fr
Nom : ERTY
Prénom : Az
Identifiant : XXX-613234-yyyy-fdgndfg-shnsf542
Date de la demande : 01-07-2024 13:39
Message :
`Message | Pas de message`

En tant que superviseur de "DEMO_IGN_SPP", vous pouvez accepter ou rejeter sa demande d'adhésion en allant sur la [page de suivante](https://cartes.gouv.fr/leboncheminpouryaller).

Cordialement, l’équipe de [cartes.gouv.fr](https://cartes.gouv.fr/)

**Comment by pprev94** [comment]
Salut @IGNF-Xavier 

Il n'est pas possible d'ajouter ce lien (/entrepot/{uuid-entrepot}/membres?userId={uuid-utilisateur}) dans l'email pour la raison suivante :
Les renseignements d'une communauté dans la liste des communautés publiques retournées par la route de l'API GET /catalogs/communities contient uniquement

`{
    "name": "Communauté Simalis NL 2024",
    "technical_name": "simalis_nl_2024",
    "contact": "deleted-96645ae5-d375-4f12-8c3a-1a22d25c6023@no_reply.ign.fr",
    "_id": "7a35fc6c-4978-4da0-abc9-196640dcf42f",
    "public": true
  }`

et pas le datastoreId

**Comment by IGNF-Xavier** [comment]
@pprev94 Est-ce que la résolution de IGNGPF-2799 permettrait d'étendre les champs recherchés au datastoredId et résoudre ce problème?

**Comment by pprev94** [comment]
Sauf si on ne veut pas exposer le datastore pour des raisons de sécurité ou autres

**Comment by slafayIGN** [comment]
Techniquement, une communauté peut ne pas être lié à un datastore. Et pourtant, on pourrait toujours y ajouter des membres. Il y a donc un problème avec notre conception de départ qui ne visait que les workflows d'alimentation-diffusion et basait toutes les urls sur l'id du datastore (dont `https://cartes.gouv.fr/entrepot/{datastoreId}/membres`). Baser les urls de gestion des membres sur la communauté est plus logique mais impose un refactoring de cette partie.

**Comment by AlexandreJaqua** [comment]
J'ai reçu une demande pour rejoindre une commu donc j'ai pu valider tout ça, c'est impec. Infos sur le demandeur + date de la demande + message + lien direct vers la modale d'ajout (et en bonus, si on clique en étant déconnecté, après la page de connexion on tombe bien dessus). Je ferme !
