### ISSUE TITLE
Erreur d'affichage de l'état de publication d'une métadonnée présente mais non publiée (aucun services)

### ISSUE THREAD

**Issue by IGNF-Xavier** [IGNF/cartes.gouv.fr#458]
### Description

PROD-Cartes.gouv, _Exposition au bruit MEL_ est en statut publié : 
![image](https://github.com/IGNF/cartes.gouv.fr/assets/98382923/5da768d5-8a26-4d92-ad9e-eb5363aa146d)
Ce sont des données qui ont été publiées puis ensuite dépubliées
La métadonnée existe dans l'entrepôt : 
![image](https://github.com/IGNF/cartes.gouv.fr/assets/98382923/04425972-05bb-438a-87db-7b21ac1f2f87)

La métadonnée n'est pas dans le catalogue : 
![image](https://github.com/IGNF/cartes.gouv.fr/assets/98382923/fc1697c6-cff9-4002-b0e0-ba7b81371163)

### Comportement attendu

La situation actuelle est cohérente : une métadonnée qui n'a plus aucun services associés ne doit plus être présente dans le catalogue publique, mais la métadonnée continue d'exister côté l'entrepôt.

Mais l'affichage dans l'espace privé ne devrait plus montrer de lien vers le catalogue et faire apparaitre la fiche comme non publiée.

### Comment reproduire l'anomalie

Dépublier tous les services d'une fiche existante.

### Solution possible

- [ ] Dans la liste des fiches de données de l'entrepôt, cette fiche devrait apparaitre comme "non publiée".
- [ ] Sur la fiche elle-même, le badge de statut de publication doit aussi être "non publiée"
- [ ] Dans l'onglet métadonnée de la fiche, le lien vers le catalogue doit être désactivé.

**Comment by slafayIGN** [comment]
Issue reformulée pour clarifier les tâches à réaliser.

Lors de l'affichage de l'onglet métadonnées avec le lien désactivé vers le catalogue, ne faut-il pas changer d'avantage l'apparence ? Avec un texte qui explique pourquoi le lien est désactivé ?

**Comment by IGNF-Xavier** [comment]
Très bonne idée. 
"Le lien vers catalogue est désactivé car la métadonnée a été dépubliée faute de services publiés"
