### ISSUE TITLE
Les pictogrammes des tuiles ne s'adaptent pas au thème sombre

### ISSUE THREAD

**Issue by slafayIGN** [IGNF/cartes.gouv.fr#459]
Sur le tableau de bord et la page d'accueil notamment : 
![image](https://github.com/IGNF/cartes.gouv.fr/assets/28899274/e5e3039d-58db-45cb-9a0c-c7999b9e85f9)

Le composant Tile de https://github.com/codegouvfr/react-dsfr/ ne peut pas gérer ça dans son état actuel, nous allons proposer une évolution : https://github.com/codegouvfr/react-dsfr/issues/150

**Comment by ocruze** [comment]
Changements apportés au composant Tile de react-dsfr :

![image](https://github.com/user-attachments/assets/a536ca5e-c706-47f6-ac47-7c57b81ad274)
