### ISSUE TITLE
Modifier la page offre

### ISSUE THREAD

**Issue by IGNF-Xavier** [IGNF/cartes.gouv.fr#464]
- [x] Designer les tableaux offre @Kristell-5 
- [x] Modifier la page offre

avec les éléments de ce contenu : 
 [page_offre_v2.docx](https://github.com/user-attachments/files/16097256/page_offre_v2.docx)

**Comment by Kristell-5** [comment]
Ci-joint, une proposition pour le tableau des offres. J'ai utilisé le composant de mise en avant qui me semble être le plus pertinent. À savoir, il est possible de changer les couleurs, soit dans les tons verts, soit dans les tons ocres. Voici le lien pour plus de détails : https://www.systeme-de-design.gouv.fr/composants-et-modeles/composants/mise-en-avant.

![image](https://github.com/IGNF/cartes.gouv.fr/assets/153001711/078ff1b9-e4ff-4bfe-8022-050321ecf1db)

**Comment by Kristell-5** [comment]
Version avec les couleurs 
![image](https://github.com/IGNF/cartes.gouv.fr/assets/153001711/5ee60dc2-6181-40cd-8ed1-3a8ef80a2ce7)

**Comment by Kristell-5** [comment]
Après échange avec @IGNF-Xavier, la solution retenue est celle avec les couleurs vert pour l'offre essentiel (gratuit) et marron pour l'offre premium (payante).

**Comment by IGNF-Xavier** [comment]
@ocruze 
Les tableaux ont la bonne couler mais leur contenu ne correspond pas au document en référence : 


![Image](https://github.com/IGNF/cartes.gouv.fr/assets/98382923/4c0aabba-05ca-448d-a8cc-6df42db03b8c)

Peux-tu
- [ ]  mettre à jour le contenu ?
- [ ] Mettre en centré offre essentielle et offre premium ?
- [ ] Mettre en centré les infos de gratuité et de payant en plus gros ?
- [ ] Faire en sorte que les tableaux utilisés aient la même taille ?

Merci

**Comment by ocruze** [comment]
@IGNF-Xavier 

Voilà, j'ai fait les changements. Est-ce que tu pourrais jeter un coup d’œil s'il te plaît ?
![image](https://github.com/IGNF/cartes.gouv.fr/assets/33525693/2ad978fb-3172-4e3c-8f9c-c3469f21a041)

**Comment by IGNF-Xavier** [comment]
Très bien

**Comment by ocruze** [comment]
Déployé en dev

**Comment by IGNF-Xavier** [comment]
Good
