### ISSUE TITLE
Modifier la page d'accueil

### ISSUE THREAD

**Issue by IGNF-Xavier** [IGNF/cartes.gouv.fr#465]
Sur : https://cartes.gouv.fr/

- [x] Modifier _pourrez_ avec _pouvez_ dans ce "Ce que vous pourrez faire avec cartes.gouv.fr"
![image](https://github.com/IGNF/cartes.gouv.fr/assets/98382923/252bd60e-cc99-4b88-bc1e-8954b6f7b7e2)
- [x] En dessous de "Ce que vous pouvez faire avec cartes.gouv.fr" , rajouter : 
`La première bêta publique de cartes.gouv.fr est désormais disponible. En tant que premiers utilisateurs, vous pouvez participer à l’amélioration des fonctionnalités (catalogue, alimentation/diffusion) en testant les pré-versions et en nous transmettant vos commentaires.`

- [x] Modifier la partie fonctionnalité ppar celle illustrée ci-dessous (maquettage @Kristell-5 à réaliser si besoin)
    - [x] Modification ordre des fonctionnalités
    - [x] Badge : "Disponible en bêta" en utilisant le badge système sans icône : https://www.systeme-de-design.gouv.fr/composants-et-modeles/composants/badge
    - [x] Modification texte : ajout des infos de disponibilité, modification d'une des fonctionnalité et son texte

![image](https://github.com/IGNF/cartes.gouv.fr/assets/98382923/59bc8713-9874-41c2-bffd-f3234a225b19)

- [x] modifier le texte illustré ci-dessous : 
![image](https://github.com/IGNF/cartes.gouv.fr/assets/98382923/fe4a9dc1-1466-46b3-b31d-0f2c1301f14f)
 par : 
_Avec cette version bêta, cartes.gouv.fr reprend de premières fonctionnalités des sites Géoservices et Géoportail ainsi que de premiers outils pour la gestion des données par les acteurs publics. Il s’enrichira progressivement de fonctionnalités nouvelles au bénéfice de tous.
Cartes.gouv.fr s’appuie sur une nouvelle infrastructure ouverte et collaborative, la Géoplateforme, soutenue par le Ministère de la Transition écologique et de la Cohésion des territoires ainsi que par le Fonds de transformation de l’action publique.
Géoservices et Géoportail restent en activité le temps que leurs fonctionnalités soient reprises dans cartes.gouv.fr.
Pour en savoir + sur cartes.gouv.fr, [rejoignez la communauté Géoplateforme](https://ign.fr/geoplateforme/rejoindre-la-communaute)._

**Comment by slafayIGN** [comment]
L'impact visuel étant conséquent, c'est pour le moment dans une branche à part `modifs-editoriales`

**Comment by Kristell-5** [comment]
Ci-joint deux propositions utilisant le composant "carte" (verticale/horizontale), sachant que nous pourrions rencontrer un problème au niveau du SIG, puisque ce sont normalement des composants cliquables. Cependant, les labels respectent les notions d'"état" ou d'"information", et la ligne noire pourrait peut-être être adaptée.(Le positionnement et les dimensions sur ces captures ne sont pas réfléchis.)


![image](https://github.com/IGNF/cartes.gouv.fr/assets/153001711/8b86586f-e085-44a2-b962-b91ed13bdd74)
![image](https://github.com/IGNF/cartes.gouv.fr/assets/153001711/2ac46289-3a70-4748-9e50-6c43d0f2ef66)

**Comment by Kristell-5** [comment]
Après échange avec @IGNF-Xavier, la solution retenue est celle avec les cartes verticales. Toutefois, il faut s'assurer que techniquement nous pouvons les faire de la même taille. Si nous n'avons pas d'autre choix que de les rendre cliquables, celles disponibles pourront renvoyer vers l'espace connecté, l'entrée carto, etc.

**Comment by ocruze** [comment]
Bonjour,
C'est le composant "tuile" plutôt non ?

Ces "cartes" dans la maquette ressemble pas mal à des "tuiles" dsfr à mon avis. Parce que dans la maquette, il y a des pictogrammes centrés, au dessus du titre et avec une marge autour, et une ligne en bas comme le composant "tuile". Tandis que le composant "carte" a un média (image/vidéo) qui prend toute la partie haute

Doc dsfr "tuile" : https://www.systeme-de-design.gouv.fr/composants-et-modeles/composants/tuile/
et "carte" : https://www.systeme-de-design.gouv.fr/composants-et-modeles/composants/carte/

dans la doc "carte" :
![image](https://github.com/IGNF/cartes.gouv.fr/assets/33525693/a3e7fbd5-e42d-4a11-b6bc-16f1d3b5987f)

Ceci dit, voici mon expérimentation :
![image](https://github.com/IGNF/cartes.gouv.fr/assets/33525693/9079332e-873b-4967-b1e6-5e6901e90c54)

gauche : le composant "carte" un peu trafiqué pour que le pictogramme soit centré et ait une marge autour
droite : le composant "tuile" sans modification

Sinon, je n'ai pas l'impression qu'elles doivent absolument être cliquables. Il y a juste une différence d'apparence quand elles sont cliquables ou non.

**Comment by IGNF-Xavier** [comment]
Est-ce possible de les rendre quand même cliquable pour les 2 tuiles disponibles en bêta ?

- [ ] La première vers l'espace connecté (forcément cela renvoie vers le connecté
- [ ] La seconde vers le catalogue

**Comment by ocruze** [comment]
L'espace connecté, c'est bien le tableau de bord ?

Tu préfères lequel ?
1. L'apparence des tuiles quand toute la tuile est cliquable :

![image](https://github.com/IGNF/cartes.gouv.fr/assets/33525693/e485ded3-308c-4441-81a3-c9aa2b8c91e3)

2. L'apparence des tuiles quand uniquement le titre est cliquable :
![image](https://github.com/IGNF/cartes.gouv.fr/assets/33525693/ea4c83dd-27be-4d01-998e-00762fe9a1d1)

**Comment by IGNF-Xavier** [comment]
Numéro 1, c'est très bien.
Fais juste attention au fait qu'on ouvre dans al même page (je te fais remarquer cela car je vois qu'il y a 2 types de flèches, l'un que je suppose ouvrir dans la même page, l'autre ouvrir dans un nouvel onglet)

**Comment by ocruze** [comment]
Ajustements faits et déployés en dev

**Comment by IGNF-Xavier** [comment]
Good
