### ISSUE TITLE
Production - pb sur page d'accueil - titres de tuiles absents

### ISSUE THREAD

**Issue by IGNF-Xavier** [IGNF/cartes.gouv.fr#493]
### Description

Sur PROD-Cartes et QLF-Cartes Il manque des titres dans les cards des briques à venir : 
![image](https://github.com/user-attachments/assets/d6523a94-1c24-46c3-a27e-e330c4d2e3d0)

### Comportement attendu

Le même comportement que DEV-Cartes
![image](https://github.com/user-attachments/assets/5085b496-a79a-40d2-baa0-f587f93aea6a)

### Comment reproduire l'anomalie

Visible sur Sur PROD-Cartes et QLF-Cartes

**Comment by slafayIGN** [comment]
Le bug est présent en v0.4.16 mais plus en v0.4.17 qui était déjà déployé en dev et que j'ai poussé vers la qlf.

Le composant Tile personnalisé qu'on utilisait en v0.4.16 n'affichait pas le titre de la tuile, si celle-ci n'avait pas de lien.

En v0.4.17 on utilise bien directement le composant Tile de react-dsfr, qui inclue la PR d'@ocruze pour que les couleurs des pictogrammes réagissent au changement de thème (voir #459)

Je passe donc cette issue à tester directement.

**Comment by IGNF-Xavier** [comment]
Ok, on peut livrer puis clore le ticket.
