### ISSUE TITLE
Offre Découverte

### ISSUE THREAD

**Issue by IGNF-Xavier** [IGNF/cartes.gouv.fr#503]
### Le besoin que vous rencontrez

Faire comprendre ce qu'est l'offre découverte

### La solution que vous aimeriez

![image](https://github.com/user-attachments/assets/5148fb14-407a-4094-897c-43d2e29ea0d2)

Sous titrer : _A des fins de tests_

Une fois dans l'espace
![image](https://github.com/user-attachments/assets/db9862d9-d1fd-43e4-b8ea-bec287e65c7b)

Indiquer entre titre et bouton : 
_Cet espace permet de tester gratuitement les fonctions d’alimentation et de diffusion de la Géoplateforme. Les conditions d'utilisation sont décrites à cette page_

Renvoyer vers les CGU

### Les alternatives que vous avez considéré

-

**Comment by ocruze** [comment]
Bonjour, voici des captures d'une première implémentation. Si pas de remarques, disponible au prochain déploiement

![image](https://github.com/user-attachments/assets/02fae995-5431-4eed-84f6-2d704a0ffe51)

![image](https://github.com/user-attachments/assets/5556ed21-ae6c-46bc-9337-b95023929b01)

**Comment by IGNF-Xavier** [comment]
Salut,
A mon sens, cela fait le travail (Il faudra juste penser en Prod de ne pas préfixer Découverte).
En y réfléchissant : juste enlever le "Gratuitement"

**Comment by slafayIGN** [comment]
Le nom de la communauté en prod est en effet préfixée par "PROD-", le dernier correctif sera donc utile dès cette semaine.

**Comment by slafayIGN** [comment]
Demandes à traiter suite à recette en qualification : 
- [ ] #505
- [ ] #506

**Comment by IGNF-Xavier** [comment]
Je clos ce ticket.
Nous en ouvrirons un spécifique à réception des CGU
