### ISSUE TITLE
Découverte - retirer la mention du catalogue (inexistant pour cet espace de travail de test)

### ISSUE THREAD

**Issue by IGNF-Xavier** [IGNF/cartes.gouv.fr#505]
### Description

![image](https://github.com/user-attachments/assets/3ec5321f-015e-4f9d-b5e1-acc7380141da)

L'encart relatif à la disponibilité de la métadonnée dans le catalogue ne devait pas être présent 

### Comportement attendu

Le remplacer par une information indiquant : 
_Les métadonnées sont désormais disponibles sur le service de découverte des métadonnées de l'offre Découverte._
Elles n'apparaitront pas sur le catalogue de cartes.gouv
Bouton **Consulter le service de métadonnées**

Le lien renvoi vers une nouvelle fenêtre avec le résultat de la requête CSW

### Comment reproduire l'anomalie

Voir données test dans le bac à sable

### Solution possible

-

### Complément de contexte

-

**Comment by ocruze** [comment]
> Le lien renvoi vers une nouvelle fenêtre avec le résultat de la requête CSW

Simplement une page qui affiche le xml de cette manière (utilise l'affichage xml du navigateur) ?

![image](https://github.com/user-attachments/assets/fcd9e189-2da2-4958-a173-8fca62651008)

**Comment by IGNF-Xavier** [comment]
Oui.

**Comment by IGNF-Xavier** [comment]
SUper merci
