### ISSUE TITLE
Découverte - Echec de génération d'une pyramide vecteur (stockage inconnu)

### ISSUE THREAD

**Issue by IGNF-Xavier** [IGNF/cartes.gouv.fr#506]
### Description

En prod-SOCLE : la génération TMS échoue de puis QLF-cartes .
L'URL en 404 est .../api/datastores/122b878c-aad8-4507-87b2-465e664467d3/pyramid/add

![image](https://github.com/user-attachments/assets/9eee2c50-b5e9-46d1-943d-ea0d4368b990)

### Comportement attendu

La génaration TMS doit fonctionner

### Comment reproduire l'anomalie

Essayer avec les données mises dans la sandbox

**Comment by slafayIGN** [comment]
@Dolite , un tag PYRAMIDE devrait être présent sur le stockage dédié à ce type de données. Peux-tu l'ajouter ?

**Comment by Dolite** [comment]
Normalement c'est bon

**Comment by slafayIGN** [comment]
Merci @Dolite 👍
