### ISSUE TITLE
Revoir la durée du cache de la liste des membres d'une communauté

### ISSUE THREAD

**Issue by slafayIGN** [IGNF/cartes.gouv.fr#508]
Lorsqu'un utilisateur est ajouté à une communauté par quelqu'un d'autre ou un autre mécanisme.
Si on est déjà allé consulté la liste des membres, on ne verra pas apparaitre ce nouveau membre même en rafraichissant la page et même si on se déconnecte et reconnecte.
L'interrogation directe de l'API confirme pourtant bien la présence de ce nouveau membre.

**Comment by IGNF-Xavier** [comment]
C'est surprenant car je viens de tester sur PROD-Cartes en supprimant AJ et en le rajoutant.
La suppression se passe bien et l'ajout aussi. Dans les 2 cas, la liste est mise-à-jour directement
