### ISSUE TITLE
[PROD Découverte] problème d'intégration en base de données sans journal

### ISSUE THREAD

**Issue by IGNF-Xavier** [IGNF/cartes.gouv.fr#509]
### Description

Au dépôt des données, le processus d'intégration des données vecteur en base est non fonctionnel.
![image](https://github.com/user-attachments/assets/2f12fe04-cbe5-42b3-9c53-7cce05222fc9)

Le rapport indique : 
![image](https://github.com/user-attachments/assets/7dfaad13-3a2b-4090-9725-2d4e8bbb1b6c)

Cela fonctionnait depuis QLF-Cartes le 18/09. En cours de vérification le 19/09

### Comportement attendu

Le processus d'intégration des données vecteur en base doit fonctionner

### Comment reproduire l'anomalie

Utiliser l'espace découverte et déposer des données

### Solution possible

vérifier les branchements au déploiement

**Comment by slafayIGN** [comment]
Le problème sur le traitement semble avoir été temporaire ou isolé. Toutes les exécutions du traitement d'intégration en base de données se sont terminées avec succès sauf 2 aujourd'hui.
Et l'intégration d'un jeu de données en échec a par la suite fonctionné, plusieurs fois.

Aucun problème de configuration de l'espace Découverte n'a été identifié pouvant avoir un lien avec ce problème.
