### ISSUE TITLE
A challenger : réaliser diverses actions pendant le téléchargement des données

### ISSUE THREAD

**Issue by IGNF-Xavier** [IGNF/cartes.gouv.fr#511]
Lorsque l'utilisateur est sur la fiche de données, le chargement peut prendre du temps : 
![Image](https://github.com/user-attachments/assets/c8cb73cb-8967-4409-b868-afd55d186676)

Il en est de même pour le dépôt de données : ![Image](https://github.com/user-attachments/assets/e7b2b332-bf05-40bd-8a04-9a9d2ca830ab)

**Option 1**
Peut-on envisager un écran splitté où il y aurait à gauche les manipulations et l'avancement du téléchargement des/dépôt des fichiers et à droite les renseignements à apporter ?
A fortiori, tout ce qui permet de remplir la fiche de métadonnées (grosse évolution en vue)

**Autre option** peut-être même meilleure
Laisser tourner les opérations lancées et notifier l'utilisateur une fois que c'est fait.
Nécessite la mise en place d'un service côté Geoplateforme.

**Comment by slafayIGN** [comment]
Système de notification par mail en attente de `IGNGPF-4462` comme pour #415 

Un changement ayant eu lieu en parallèle avec #518 (en prod avec la v0.5.9 du 10/10/2024), je suggère de clore cette demande qui la doublonne en grande partie.
