### ISSUE TITLE
Fiche de données innaccessibles quand on supprime le dernier (ou le seul) service publié

### ISSUE THREAD

**Issue by slafayIGN** [IGNF/cartes.gouv.fr#513]
### Description

La fiche n'est plus accessible avec le message d'erreur

```
o.endpoints[0] is undefined
```

### Comportement attendu

La fiche devrait rester accessible car il y a toujours des entités (stored_data, upload...) présentent.

### Comment reproduire l'anomalie

Se produit sur tous les datastores, y compris Découverte.
Publier une flux simple, puis le supprimer sans supprimer la fiche complète.

**Comment by IGNF-Xavier** [comment]
Ok sur DEV-Cartes bac à sable
@AlexandreJaqua peux-tu tester sur QLF-Cartes sur PROD-socle (découverte et datastore attribué)

**Comment by IGNF-Xavier** [comment]
OK :
![image](https://github.com/user-attachments/assets/a33259b0-973f-43c7-be29-9a0ea765a7b2)
