### ISSUE TITLE
Impossible de créer une permission sans date d'expiration

### ISSUE THREAD

**Issue by slafayIGN** [IGNF/cartes.gouv.fr#514]
### Description

Le champ "date d'expiration" des formulaires d'ajout et de modification de permission signale qu'il est optionnel.

Il a plusieurs défauts : 

- il est difficile à vider : il faut le faire pour jour / mois / année qui apparaissent d'abord invalides puis sous forme de placeholder (en gris) DD/MM/YYYY.
- une fois (laborieusement) vidé, il n'est pas possible de soumettre le formulaire, sans erreur affichée à l'utilisateur

### Comportement attendu

Idéalement on  devrait pouvoir vider ce champ en une seule action : soit un clic sur un bouton vider, soit un appui sur la touche Suppr ou Backspace quand on a sélectionné la valeur.

Edit : il y a en réalité un bouton "Effacer" dans le datepicker => repéré tardivement car le datepicker s'ouvre avec une icône à droite du champ (parfois loin de là où on saisie réellement si le champ est large), donc l'action au clavier

On devrait pouvoir créer une permission sans date d'expiration.

### Comment reproduire l'anomalie

Dans un espace de travail qui a au moins un service privé publié, se rendre dans le menu Gérer l'espace de travail > Permissions accordées, puis essayer l'un l'ajout d'une permission ou la modification d'une clé existante.

**Comment by AlexandreJaqua** [comment]
Globalement ça marche : si je clique sur la croix pour le vider d'un seul coup, c'est rapide et ça ne crée pas d'erreur, je parviens bien à créer la permission.
![image](https://github.com/user-attachments/assets/be32d61a-6f42-4780-8c9f-5dc659e32905)

Cependant si je choisis la méthode compliquée et que je supprime "manuellement" la date pré-indiquée (en la sélectionnant puis Suppr ou Backspace), le problème subsiste, la valeur vide est toujours indiquée comme erronée.
![image](https://github.com/user-attachments/assets/8b3d4dfc-fac9-402d-8e0a-628c174235da)

**Comment by AlexandreJaqua** [comment]
Yes c'est parfait merci, je ferme
