### ISSUE TITLE
Après lancement de l'intégration en base de données, permettre à l'utilisateur de naviguer ailleurs

### ISSUE THREAD

**Issue by IGNF-Xavier** [IGNF/cartes.gouv.fr#518]
L'étape d'intégration en base de données est très longue.
![Image](https://github.com/user-attachments/assets/1353e738-77cb-4c0b-8bc9-7901afd6d0b3)

Une fois l'étape atteinte, il faut :

- [x]  indiquer à l'utilisateur que l'intégration est en cours
- [ ] lui permettre de quitter la modale (en redirigeant vers la fiche de données, onglet données) via un bouton qui apparaitrait une fois le traitement lancé : 
  - texte à ajouter sous la dernière étape : "Vous pouvez maintenant poursuivre votre navigation même si vos données ne sont pas encore prêtes"
  - texte du bouton : "Consulter la fiche de données" - (bouton sur fond bleu)
- [ ] dans l'onglet données, afficher la base en cours de génération (⚠️ à la mise en page qui casse avec ce long statut) plutôt que l'upload qui portait un bouton "reprendre l'intégration" (cette action n'aurait plus de raison d'être)
- [ ] vérifier régulièrement directement depuis cette page l'état de la base (c'est déjà fait) une fois l'intégration terminée on aboutit au même affichage que d'habitude : une base avec son statut Prêt.

**Comment by ocruze** [comment]
![image](https://github.com/user-attachments/assets/cb928a2b-34d7-44b1-afca-298ea269790c)

![image](https://github.com/user-attachments/assets/50287b80-4dae-4e3f-819e-11909b6156df)

![image](https://github.com/user-attachments/assets/27210f43-e042-4c16-a238-07947894500a)

**Comment by IGNF-Xavier** [comment]
Consulter la fiche de donnée : renvoie vers la fiche de donnée?
Revenir vers mes données : renvoie vers la liste des données ?
Je suggère de n'avoir qu'un bouton vers "Consulter la fiche de données, onglet jeux de données activé, ce qui permettra de voir le résultat en cours de génération.

En tout cas, merci pour la réactivité

**Comment by ocruze** [comment]
D'accord, bouton retour vers mes données retiré et bouton consulter la fiche de données renvoie vers l'onglet jeux de données

![image](https://github.com/user-attachments/assets/b6ff8927-12cd-4934-9ba0-b67034dd587f)

**Comment by IGNF-Xavier** [comment]
Parfait. Merci

**Comment by IGNF-Xavier** [comment]
FOnctionne
