### ISSUE TITLE
Désactiver l'étape de téléchargement de fichier métadonnées

### ISSUE THREAD

**Issue by IGNF-Xavier** [IGNF/cartes.gouv.fr#519]
Au moment de la configuration d'un service, est proposé le chargement d'une métadonnée.
A date non fonctionnel

Option 1 : conserver la page et mettre à venir
Option 2 : supprimer la page

**Comment by ocruze** [comment]
On met quoi comme texte d'explication ? @IGNF-Xavier

**Comment by IGNF-Xavier** [comment]
`Fonctionnalité en cours de construction`

Je ne préfère pas rentrer dans les détails. Ceux qui connaissent les métadonnées comprendront, les autres passeront leur chemin sans s'attarder

**Comment by ocruze** [comment]
![image](https://github.com/user-attachments/assets/68190a46-f731-4670-a12d-6a0e39942c15)

**Comment by IGNF-Xavier** [comment]
Juste une petite modification : je suggère d'utiliser la mise en exergue du DSFR : 
https://www.systeme-de-design.gouv.fr/composants-et-modeles/composants/mise-en-exergue

![image](https://github.com/user-attachments/assets/011d13e3-07cf-4e6a-9c74-409da17d687b)

**Comment by slafayIGN** [comment]
Avec une couleur illustrative particulière ?
https://www.systeme-de-design.gouv.fr/fondamentaux/couleurs-palette/#accent (la bordure peut prendre la couleur "main" de chacun de ces thèmes : green-tilleul-verveine, orange-terre-battue, purple-glycine.... Sinon elle reste bleu par défaut)

Ce n'est pas une alerte 'attention' ou 'information' que tu voudrais utiliser plutôt ?
https://www.systeme-de-design.gouv.fr/composants-et-modeles/composants/alerte

**Comment by IGNF-Xavier** [comment]
Oui la version information.J'ai hésité effectivement.
Le 2 oct. 2024 14:47, Sylvain Lafay a écrit :


Avec une couleur illustrative particulière ?
https://www.systeme-de-design.gouv.fr/fondamentaux/couleurs-palette/#accent (la bordure peut prendre la couleur "main" de chacun de ces thèmes : green-tilleul-verveine, orange-terre-battue, purple-glycine.... Sinon elle reste bleu par défaut)

Ce n'est pas une alerte 'attention' ou 'information' que tu voudrais utiliser plutôt ?
https://www.systeme-de-design.gouv.fr/composants-et-modeles/composants/alerte

**Comment by IGNF-Xavier** [comment]
Fonctionne.
Reste juste à mettre en forme alerte

**Comment by AlexandreJaqua** [comment]
All good, merci ! Forme alerte sur le message + le reste de la fonctionnalité est bien grisée.
![Image](https://github.com/user-attachments/assets/f24eec2d-4f65-484d-a6ad-304beb172a40)
