### ISSUE TITLE
Chargement par morceau du tableau de bord

### ISSUE THREAD

**Issue by slafayIGN** [IGNF/cartes.gouv.fr#521]
Le tableau de bord met du temps à s'afficher parce que l'affichage de l'ensemble de son contenu est soumis à l'attente du chargement de la liste des entrepôts.

Cette requête est longue car derrière le `GET /users/me`, chaque entrepôt de l'utilisateur est récupéré (`GET /datastores/{datastore}`) pour vérifier qu'il est bien utilisable.

```ts
 {datastoreListQuery.isLoading ? (
     <LoadingText />
 ) : (
    <>
        "Tout le contenu"
    </>
)}
```

Seule la section "Mes espaces de travail" ([/assets/entrepot/pages/dashboard/DashboardPro.tsx#L89-L103](https://github.com/IGNF/cartes.gouv.fr/blob/main/assets/entrepot/pages/dashboard/DashboardPro.tsx#L89-L103)) a réellement besoin d'attendre que cette requête aboutisse.

Le reste de la page peut s'afficher sans requête à l'API à l'exception du prénom de l'utilisateur qui arriverait dans un `GET /users/me` plus rapide.

Un refactoring de cette page pour ne plus faire dépendre la totalité de son affichage de la recherche des datastores accélèrerait probablement son rendu. (ticket plus large en référence : #461)

**Comment by AlexandreJaqua** [comment]
Après un premier test ça me semble effectivement bien plus rapide !
