### ISSUE TITLE
Interdire les namespaces WFS commançant par un chiffre

### ISSUE THREAD

**Issue by slafayIGN** [IGNF/cartes.gouv.fr#523]
Une couche publiée commençant par un chiffre a mis en difficulté le GetCapabilities du endpoint WFS.

L'API Entrepôt (configuration) doit évoluer pour que la propriété `layer_name` interdise cela. Sa regex actuelle est `^[A-Za-z0-9_\-.]+$`.

L'interface peut également filtrer ce champ.

Il semblerait que la spécifications pour ce champs soit plutôt un NCName : http://www.datypic.com/sc/xsd/t-xsd_NCName.html

(Dans ce cas commencer par un - ou un . aurait également mis en échec le WFS)

**Comment by Dolite** [comment]
Oui c'est bien ce champ là. Le contrôle est en cours et se fera de la même manière sur le layer name pour tous les types de configuration.
