### ISSUE TITLE
Métadonnées : Revoir le choix de la résolution spatiale

### ISSUE THREAD

**Issue by IGNF-Xavier** [IGNF/cartes.gouv.fr#529]
![Image](https://github.com/user-attachments/assets/9d9a567a-e5cb-4b47-ad20-492772068f50)

La liste proposée correspond à des échelles d'équivalence de produits IGN papier.
@MarieLambois :
- Peux-tu nous confirmer de quoi il s'agit : une échelle de validité des données?
- Quelles items dans la liste de choix devons-nous mettre?

Merci

**Comment by slafayIGN** [comment]
Ce champ est aujourd'hui rempli avec une valeur entière qui correspond à un dénominateur d'échelle : 
```xml
  <gmd:spatialResolution>
      <gmd:MD_Resolution>
          <gmd:equivalentScale>
              <gmd:MD_RepresentativeFraction>
                  <gmd:denominator>
                      <gco:Integer>{{ resolution }}</gco:Integer>
                  </gmd:denominator>
              </gmd:MD_RepresentativeFraction>
          </gmd:equivalentScale>
      </gmd:MD_Resolution>
  </gmd:spatialResolution>
```

Dont les valeurs sont proposées comme une liste finie aux utilisateurs mais sous la forme d'un nom. Voici les correspondances entre le nom et le dénominateur de l'échelle : 
```json
{
    "Nationale": 1000000,
    "Régionale": 250000,
    "Départementale": 150000,
    "Top 200": 200000,
    "Top 100": 100000,
    "Top 75": 75000,
    "Top 25": 25000
}
```

La maquette était différente : 

![image](https://github.com/user-attachments/assets/267be25b-1cc6-4765-b684-2eb4d5151c8a)

Une décision (dont je ne retrouve pas la trace) est intervenue entre la réalisation de la maquette et la première implémentation par les dev en août 2023 car il n'y a jamais eu d'autre fonctionnement dans le code. Il n'y a d'ailleurs eu aucun changement ici depuis cette première implémentation il y a plus d'un an.

L'équipe de dev attends une nouvelle proposition pour rendre le remplissage de ce champ plus clair : 
- nouvel intitulé (je propose : "Résolution spatiale")
- nouveau texte d'aide (je propose, nous sommes uniquement dans le cas de données vecteur : "Echelle approximative à laquelle les données sont les plus pertinentes. Exemple : 25000 si les données sont faites pour un affichage à l'échelle d'une carte topographique")
- nouvelle façon de saisir la valeur (si la liste déroulante et les valeurs ne conviennent pas. Si on préfère une saisie libre d'un entier, je propose de tenter de représenter un "1:" avant le champ)

**Comment by IGNF-Xavier** [comment]
✅ Résolution spatiale
✅ Echelle approximative à laquelle les données sont les plus pertinentes. Exemple : 25000 si les données sont faites pour un affichage à l'échelle d'une carte topographique

La saisie libre d'un entier peut être source d'erreur. Et qui plus est pour les plus curieux, objet de résolution exotique telles que celles des seuils de zoom.

@MarieLambois est-on couvrant si on propose : 

"1:" + sélecteur
Sélecteur = 2 000, 5 000, 10 000, 25 000, 50 000, 100 000, 250 000, 500 000, 1 000 000, 5 000 000, 10 000 000

**Comment by MarieLambois** [comment]
Je dirai qu'il faut descendre plus bas : https://www.geocatalogue.fr/geonetwork/srv/fre/catalog.search#/metadata/3e065511-eb8c-4008-8725-a614d86b2deb 
Sur les paliers ça me parait pas mal. Pour info le Geocatalogue a ça en données vecteur :
![image](https://github.com/user-attachments/assets/55e26c17-1438-4965-abb7-8ddace98853d)
![image](https://github.com/user-attachments/assets/2443a935-c20e-43e5-98a1-dc7bdda82179)

**Comment by IGNF-Xavier** [comment]
> ✅ Résolution spatiale ✅ Echelle approximative à laquelle les données sont les plus pertinentes. Exemple : 25000 si les données sont faites pour un affichage à l'échelle d'une carte topographique
> 
> La saisie libre d'un entier peut être source d'erreur. Et qui plus est pour les plus curieux, objet de résolution exotique telles que celles des seuils de zoom.
> 
> @MarieLambois est-on couvrant si on propose :
> 
> -- **Modification avec rajout d'échelle "1:" + sélecteur Sélecteur =_200, 500, 1 000, 2 000, 5 000, 10 000, 25 000, 50 000, 100 000, 250 000, 500 000, 1 000 000, 5 000 000, 10 000 000**

L'implémentation ne correspond pas à ce qui était demandé. Les précisions de comparaison par Marie ont du perturbé la bonne prise en compte de la demande
